# Page settings

baseurl = "https://blog.jasperginn.nl/"
languageCode = "en-us"
title = "Jasper Ginn CV"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-XXXXXXX-Y"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Hugo Responsive Resume/CV Theme for Developers"
    author = "Pavel Kanyshev"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # itâ€™s quick and easy to change the styling and colour scheme.

    styles = "styles-6.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Jasper Ginn"
        tagline = "Data Scientist / Student"
        avatar = "https://media.licdn.com/dms/image/C5603AQHppzdTh0lceA/profile-displayphoto-shrink_200_200/0?e=1539820800&v=beta&t=IZF4-7yaWAbCq_j0swkL8al8FprW4J-Bw-9Odm4vcNg"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto:jasperginn@gmail.com"
        title = "jasperginn@gmail.com"

        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "https://www.jasperginn.nl"
        title = "jasperginn.nl"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/jasperginn"
        title = "in/jasperginn"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/JasperHG90"
        title = "github.com/JasperHG90"

        [[params.contact.list]]
        class = "twitter"
        icon = "fa-twitter"
        url = "//twitter.com/username"
        title = "@JHGinn"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "MSc, Methodology & Statistics"
        college = "Utrecht University"
        dates = "2018 - present"

        [[params.education.list]]
        degree = "BSc, Liberal Arts & Sciences"
        college = "Leiden University"
        dates = "2011 - 2014"
        
    # professional development
    [params.development]
        enable = true
        title = "development"
        
        [[params.development.list]]
        degree = "Deep Learning Specialization"
        college = "Coursera (deeplearning.ai)"
        dates = "August 2018 - Present"
        certificate = "https://www.coursera.org/specializations/deep-learning"

        [[params.development.list]]
        degree = "UT.5.05x: LAFF: Linear Algebra - Foundations to Frontiers"
        college = "edX (University of Texas)"
        dates = "May 2018"
        certificate = "https://courses.edx.org/certificates/d86f74f75f1c41e486313d41a80768a0"
        
        [[params.development.list]]
        degree = "DAT201x: Querying with Transact-SQL"
        college = "edX (Microsoft)"
        dates = "Apr. 2017"
        certificate = "https://courses.edx.org/certificates/9634e8b4db1a4c98a896f23fd52e1872"

        [[params.development.list]]
        degree = "Machine Learning"
        college = "Coursera (Stanford University)"
        dates = "Nov. 2016"
        certificate = "https://www.coursera.org/account/accomplishments/verify/HGE62SSYGFCK"
        
        [[params.development.list]]
        degree = "Machine Learning With Big Data"
        college = "Coursera (UC San Diego)"
        dates = "Jun. 2016"
        certificate = "https://www.coursera.org/account/accomplishments/verify/PAQBLPZTU3YN"
        
        [[params.development.list]]
        degree = "Introduction to Big Data Analytics"
        college = "Coursera (UC San Diego)"
        dates = "Apr. 2016"
        certificate = "https://www.coursera.org/account/accomplishments/verify/WJQF2E5AUYYU"
        
        [[params.development.list]]
        degree = "Hadoop Platform and Application Framework"
        college = "Coursera (UC San Diego)"
        dates = "Nov. 2015"
        certificate = "https://www.coursera.org/account/accomplishments/verify/3NWYMEW55HEL"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "English"
        level = "Native"

        [[params.language.list]]
        language = "Dutch"
        level = "Native"

        [[params.language.list]]
        language = "German"
        level = "Elementary"

    # Interests section
    # TURN INTO PROFESSIONAL DEVELOPMENT
    [params.interests]
        enable = false
        title = "Interests"

        [[params.interests.list]]
        interest = "Climbing"

        [[params.interests.list]]
        interest = "Cooking"

        [[params.interests.list]]
        interest = "Cooking"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "A data scientist with a versatile background and a strong interest in social and behavioural sciences, finance, artificial intelligence and social good. Experience with project management, data dashboards, consultancy, machine learning and academic writing."

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Research intern"
        dates = "June - August 2018"
        company = "Cortical.io, Vienna"
        details = "Investigated the application of Cortical.io's core technologies to finance & investing. Focused on: <br><br> <ul><li>Gaining an in-depth understanding of Cortical.io's core technology and its application to large, textual datasets.</li><li>Develop methods to process, store and query news articles using Cortical.io's semantic folding technology</li><li>Use these methods to develop a prototype for visualizing and downloading historical and live data representing the nature and quantity of news relevant to user-selected stocks, commodities and portfolios.</li><li>Serving as liaision between the research team led by Prof. David Stolin and Cortical.</li></ul>"
        
        [[params.jobs.list]]
        position = "Data Analyst"
        dates = "2015 - 2017"
        company = "Leiden University Centre for Innovation, The Hague"
        details = "Data analyst at the Leiden Center for Innovation, Online Learning Lab (OLL). The OLL facilitates the development of Massive Open Online Courses (MOOCs) at Leiden University. I was responsible for retrieving, storing and analysing MOOC data with the aim of improving courses and providing feedback to content creators & academics. Co-published several academic articles with researchers and published open-source tools for analysing MOOC data."

        [[params.jobs.list]]
        position = "UI Developer"
        dates = "2012 - 2014"
        company = "Amazon, London"
        details = "**Describe your role here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem."

    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Projects"
        intro = "**You can list your side projects or open source libraries in this section.** Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et ligula in nunc bibendum fringilla a eu lectus"

        [[params.projects.list]]
        title = "qualtRics"
        url = "https://github.com/ropensci/qualtRics"
        tagline = "Library that provides a bridge between the [qualtrics](https://www.qualtrics.com/) API and R"

        [[params.projects.list]]
        title = "sfutils"
        url = "https://jasperhg90.github.io/sfutils/"
        tagline = "R package to work with [semantic fingerprints](http://www.cortical.io/science-semantic-folding.html) developed by Cortical.io"
        
        [[params.projects.list]]
        title = "FinTxtClient"
        url = "https://github.com/FinTxt/FinTxtClient-Py"
        tagline = "Python and [R](https://github.com/FinTxt/FinTxtClient-R) modules that allows the user to interact with the [FinTxt.io API](https://api.fintxt.io/rest/__swagger__/)"
        
    # Publications section
    [params.publications]
        enable = true
        icon = "fa-book"
        title = "publications"
        
        [[params.publications.list]]
        publisher = "Proceedings of the 8th International Conference on Learning Analytics and Knowledge. ACM, 2018."
        authors = "van der Zee, Tim, et al."
        title = "Evaluating retrieval practice in a MOOC: how writing and reading summaries of videos affects student learning"
        year = "2018"
        
        [[params.publications.list]]
        authors = "Ginn, J.H."
        year = 2018
        title = "qualtRics: retrieve survey data using the Qualtrics API"
        publisher = "Journal of Open Source Software, 3(24), 690, https://doi.org/10.21105/joss.00690"
        
        [[params.publications.list]]
        publisher = "In Proceedings of the Fourth (2017) ACM Conference on Learning@ Scale. ACM, 2017."
        title = "Learning about Learning at Scale: Methodological Challenges and Recommendations"
        authors = "Van der Sluis, Frans, Tim Van der Zee, and Jasper Ginn"
        year = "2017"
        
        [[params.publications.list]]
        publisher = "In Proceedings of the Third (2016) ACM Conference on Learning@ Scale (pp. 51-60). ACM."
        title = "Explaining Student Behavior at Scale: The influence of video complexity on student dwelling time"
        authors = "Van der Sluis, F., Ginn, J., & Van der Zee, T."
        year = "2016"

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "R"
        level = "90%"
                
        [[params.skills.list]]
        skill = "Python"
        level = "75%"

        [[params.skills.list]]
        skill = "SQL"
        level = "50%"

        [[params.skills.list]]
        skill = "NoSQL"
        level = "40%"

        [[params.skills.other]]
        skill = "Shiny"
        
        [[params.skills.other]]
        skill = "Markdown"
        
        [[params.skills.other]]
        skill = "Plumber"
        
        [[params.skills.other]]
        skill = "Docker"
        
        [[params.skills.other]]
        skill = "Pandas"
        
        [[params.skills.other]]
        skill = "Tensorflow"
      
        [[params.skills.other]]
        skill = "Linux"
        
        [[params.skills.other]]
        skill = "Git"
        
    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = "Jasper Ginn"
