baseurl = "https://blog.jasperginn.nl/"
languageCode = "en-us"
title = "Natrium Theme"
theme = "hugo-natrium-theme"
preserveTaxonomyNames = true
rssLimit = 10
paginate = 10
pygmentsCodefences = true
pygmentsStyle = "native"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[taxonomies]
    category = "categories"  
    tag = "tags"

[permalinks]
    post = "/:slug/"
    page = "/:slug/"
    
[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = -120

[[menu.main]]
    name = "Categories"
    url = "/categories"
    weight = -130
