languageCode = "en-us"
title = "Aerial"
baseurl = "https://www.jasperginn.nl/"
theme = "aerial"

[params]
  name = "Jasper Ginn"
  about = "Data Scientist &nbsp;&bull;&nbsp; Student Applied Statistics &nbsp;&bull;&nbsp; R/Python Developer"
  copyright = "Jasper Ginn"
  favicon = "favicon.ico"

#[[params.social]]
#  medium = "blog"
#  icon = "wordpress"
#  link = "https://www.jasperginn.nl/blog"
  
[[params.social]]
  medium = "cv"
  icon = "file"
  link = "https://www.jasperginn.nl/cv"

[[params.social]]
  medium = "Email"
  icon = "envelope-o"
  link = "mailto:jasperginn@gmail.com"

[[params.social]]
  medium = "linkedin"
  icon = "linkedin"
  link = "https://nl.linkedin.com/in/jasperginn"
  
[[params.social]]
  medium = "Twitter"
  icon = "twitter"
  link = "https://twitter.com/jhginn?lang=en"
  
[[params.social]]
  medium = "Github"
  icon = "github"
  link = "https://github.com/JasperHG90"
  
[[params.social]]
  medium = "docker"
  icon = "docker"
  link = "https://hub.docker.com/u/jhginn/"
